"""Generating `/etc/samba/smbpal.conf` — the file SMBPal owns completely.

§3a's bargain: we never touch the user's shares and never parse their file.
Ours are ours. That only holds if this file is generated whole, every time,
from config — never edited in place.

M0 §1a is the other half: a malformed or missing file here costs the user *our*
shares and nothing else. `smbd` starts, stays active, and their shares keep
serving. That is reassuring, and it is also why `testparm` cannot tell us we
got this wrong — see `control.verify_present`.
"""

from __future__ import annotations

from typing import Any, Iterable

from smbpal.errors import SmbpalError

HEADER = """\
# Generated by SMBPal. Do not edit.
#
# This file is rewritten in full whenever a share changes. SMBPal owns it
# completely and never parses or modifies /etc/samba/smb.conf beyond the one
# marked include block that points here.
"""


class GenerationRefused(SmbpalError):
    """A value reached the generator that must never be written to a config file."""

    code = "generation_refused"


def render(shares: Iterable[dict[str, Any]]) -> str:
    """Render the enabled shares as Samba sections."""
    sections = [HEADER]
    for share in shares:
        if not share.get("enabled", True):
            continue
        sections.append(_render_share(share))
    return "\n".join(sections)


def _render_share(share: dict[str, Any]) -> str:
    name = _safe(share, "name")
    path = _safe(share, "path")
    lines = [
        f"[{name}]",
        f"   path = {path}",
        f"   read only = {'yes' if share.get('read_only') else 'no'}",
        "   browseable = yes",
        # M0 §1 found `map to guest = bad user` and `usershare allow guests = yes`
        # shipped enabled on Pi OS, so a share is guest-readable unless it says
        # otherwise. Ours say otherwise.
        "   guest ok = no",
    ]
    user = share.get("credential_ref")
    if user:
        lines.append(f"   valid users = {_safe(share, 'credential_ref')}")
    return "\n".join(lines) + "\n"


def _safe(share: dict[str, Any], key: str) -> str:
    """Last gate before bytes reach a config file.

    The schema already rejects these, and a share name carrying a newline is
    arbitrary `smb.conf`. Checking again here costs nothing and means the
    generator is safe even if it is ever called with a document that did not
    come through validation.
    """
    value = share.get(key)
    if not isinstance(value, str) or not value:
        raise GenerationRefused(f"share {share.get('id')!r} has no usable {key}")
    if any(char in value for char in "\n\r\x00"):
        raise GenerationRefused(
            f"share {share.get('id')!r} has a {key} containing a line break",
            detail="This should have been caught by validation. Refusing to "
            "write it either way.",
        )
    return value
