"""What is on this machine that the config does not account for.

A Pi run on 27 August 2026 started the daemon against an empty config while
`/mnt/smbpal-test` was mounted and its automount enabled. `connection list` was
correct — nothing *is* configured — and useless, because the machine was still
mounting a share on access and SMBPal had nothing to say about it.

**Three classes, because the action differs.** "Managed or not" is the obvious
split and it collapses the case that caused the confusion:

    managed     in the config. Everything else in this package is about these.
    orphaned    our unit, no config entry. An enabled automount that nobody is
                looking at will keep mounting on access, forever, with nothing
                in the config saying so. This is worse than a stranger's mount,
                not the same — and it is ours to clean up.
    unmanaged   a cifs mount that is not ours. §8 parks adopting these for
                Phase 1, so they are reported and never touched.

**The scan reads units as well as mounts, and it has to.** An orphaned
automount that has never been triggered appears in `mountinfo` only as autofs
— nothing identifies it — but it will mount on the next `ls`. Units are where
that is visible, because ours carry a marker naming the connection they were
written for.

**And ownership is only provable while the unit exists.** A cifs line in
`mountinfo` carries a source and a filesystem type; nothing in it says SMBPal
made the mount. The marker in the unit file is the only evidence, so a unit
removed while its mount is still up demotes an orphan we could have cleaned up
into an unmanaged mount we may not touch. That is why `_remove_stale_units`
verifies the unmount before it unlinks.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from smbpal.mounts import probe as probe_module

# Kept in step with apply.MARKER by a test; imported lazily to avoid a cycle.
MARKER = "# Generated by SMBPal for connection "

ORPHANED = "orphaned"
UNMANAGED = "unmanaged"

_WHERE = re.compile(r"^Where=(.*)$", re.MULTILINE)


@dataclass(frozen=True)
class Finding:
    """One thing on the machine that the config does not describe."""

    kind: str
    mountpoint: str
    # `//host/share` when something is mounted. Empty for an armed automount
    # that has never fired: the unit knows, but nothing is mounted to ask.
    source: str
    mounted: bool
    # The connection id the unit was written for, from its marker. Present only
    # for orphans — it is the evidence that this was ours.
    connection_id: str | None = None
    unit: str | None = None

    def to_wire(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "mountpoint": self.mountpoint,
            "source": self.source,
            "mounted": self.mounted,
            "connection_id": self.connection_id,
            "unit": self.unit,
        }

    @property
    def message(self) -> str:
        if self.kind == ORPHANED:
            state = "mounted" if self.mounted else "armed, and will mount on access"
            return (
                f"SMBPal wrote this for connection {self.connection_id!r}, which is "
                f"no longer in the config. It is {state}. `smbpal apply` removes it"
            )
        return (
            "not created by SMBPal, so it is left alone. Remove it with the tool "
            "that made it, or by hand"
        )


def _marked_units(unit_dir: Path) -> list[tuple[str, str, str]]:
    """(unit name, mountpoint, connection id) for every unit we wrote."""
    found: list[tuple[str, str, str]] = []
    if not unit_dir.is_dir():
        return found
    for path in sorted(unit_dir.iterdir()):
        if path.suffix not in (".mount", ".automount"):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        if MARKER not in text:
            continue
        where = _WHERE.search(text)
        if where is None:
            continue
        identifier = text.split(MARKER, 1)[1].split(".", 1)[0].strip()
        found.append((path.name, os.path.normpath(where.group(1).strip()), identifier))
    return found


def survey(
    config: dict[str, Any],
    *,
    unit_dir: Path | str,
    mountinfo: Path | str = probe_module.DEFAULT_MOUNTINFO,
) -> list[Finding]:
    """Everything on the machine that `config` does not account for.

    Scoped to SMB. An NFS or ext4 mount somewhere unexpected is not SMBPal's
    business and reporting it would be noise dressed as diligence.
    """
    configured = {
        os.path.normpath(c["mountpoint"])
        for c in config.get("connections", [])
        if c.get("mountpoint")
    }

    entries = probe_module.mount_entries(mountinfo) or []
    mounted: dict[str, probe_module.MountEntry] = {
        os.path.normpath(e.mountpoint): e
        for e in entries
        if e.fstype == probe_module.CIFS
    }

    findings: list[Finding] = []
    claimed: set[str] = set()

    for unit, mountpoint, identifier in _marked_units(Path(unit_dir)):
        if mountpoint in configured or mountpoint in claimed:
            continue
        claimed.add(mountpoint)
        entry = mounted.get(mountpoint)
        findings.append(
            Finding(
                kind=ORPHANED,
                mountpoint=mountpoint,
                source=entry.source if entry else "",
                mounted=entry is not None,
                connection_id=identifier or None,
                unit=unit,
            )
        )

    for mountpoint, entry in sorted(mounted.items()):
        if mountpoint in configured or mountpoint in claimed:
            continue
        findings.append(
            Finding(
                kind=UNMANAGED,
                mountpoint=mountpoint,
                source=entry.source,
                mounted=True,
            )
        )

    return findings
