"""Generating the systemd `.mount` and `.automount` units for a connection.

M0 §4 mounted `//rivendell.local/Media` on `/mnt/m0` by hand and watched what
happened; these units are that, generated. What it observed shapes them:

- **The mount happened 80 seconds after boot, on first access** — not during
  boot. `systemd-analyze blame` put `mnt-m0.mount` at 541 ms, well behind
  `NetworkManager-wait-online` at 5.985 s. An automount unit is why, and it is
  why boot is not delayed by a NAS that is switched off.
- **`soft` was the default**, and it explains every failure result: the call
  eventually fails rather than blocking forever.
- **`TimeoutIdleSec` may never fire on a desktop.** The automount was
  re-triggered 80 s after boot by a background desktop process (pid 1653,
  `pool-6`), not by the user. Idle unmounting cannot be relied on, so it is not
  set here — an unmount that never happens is not a failure, but a design that
  assumes it will is.
"""

from __future__ import annotations

import re
import string
from typing import Any

_ALLOWED = set(string.ascii_letters + string.digits + ":_.")
_SLASHES = re.compile(r"/+")


def escape_path(path: str) -> str:
    """systemd's path escaping — what `systemd-escape -p` produces.

    Implemented rather than shelled out so it is testable anywhere and so unit
    naming does not depend on a subprocess. The rules: collapse and strip
    slashes, the empty path is `-`, `/` becomes `-`, a leading `.` becomes
    `\\x2e`, and every other byte outside `[A-Za-z0-9:_.]` — **including `-`,
    because it is the separator** — becomes `\\xNN`.

    **Verified against `systemd-escape -p --suffix=mount` on Pi OS, 20 August
    2026** for `/mnt/m0`, `/mnt/my-share`, `/.dotdir` and `/srv/a b` — all four
    agree. Multi-byte UTF-8 is still only the documented per-byte rule and has
    not been checked against real systemd.
    """
    collapsed = _SLASHES.sub("/", path).strip("/")
    if not collapsed:
        return "-"

    out: list[str] = []
    for index, byte in enumerate(collapsed.encode("utf-8")):
        char = chr(byte)
        if char == "/":
            out.append("-")
        elif index == 0 and char == ".":
            # A unit named `.something` would be a hidden file to half the
            # tools that look at /etc/systemd/system.
            out.append("\\x2e")
        elif char in _ALLOWED and byte < 128:
            out.append(char)
        else:
            out.append(f"\\x{byte:02x}")
    return "".join(out)


def unit_names(mountpoint: str) -> tuple[str, str]:
    """Return (mount unit, automount unit) for a mountpoint."""
    escaped = escape_path(mountpoint)
    return f"{escaped}.mount", f"{escaped}.automount"


def mount_options(connection: dict[str, Any], credentials_path: str | None) -> str:
    options = [
        # Explicit even though M0 found it the default. It is the option that
        # decides what happens when the remote disappears, so it should not be
        # something a distribution can change under us.
        "soft",
        "_netdev",
        "iocharset=utf8",
        "file_mode=0755",
        "dir_mode=0755",
    ]
    if credentials_path:
        # §10.6: the credential goes in a 0600 file whose *path* is the
        # argument. M0 §9 is the reason — sudo journals full command lines, and
        # ps shows arguments to anyone at all.
        options.append(f"credentials={credentials_path}")
    else:
        options.append("guest")
    uid = connection.get("uid")
    gid = connection.get("gid")
    if uid is not None:
        # forceuid/forcegid because the server's idea of ownership is not ours;
        # M0 saw the mount carry uid=1000,forceuid,gid=1000,forcegid.
        options.extend([f"uid={uid}", "forceuid"])
    if gid is not None:
        options.extend([f"gid={gid}", "forcegid"])
    return ",".join(options)


def mount_unit(connection: dict[str, Any], credentials_path: str | None) -> str:
    what = f"//{connection['host']}/{connection['share']}"
    return f"""\
# Generated by SMBPal for connection {connection['id']}. Do not edit.
[Unit]
Description=SMBPal mount of {what}
# The remote is on the network but the automount means nothing waits for it:
# the mount happens on first access, not during boot (M0 §4).
After=network-online.target
Wants=network-online.target

[Mount]
What={what}
Where={connection['mountpoint']}
Type=cifs
Options={mount_options(connection, credentials_path)}

[Install]
WantedBy=multi-user.target
"""


def automount_unit(connection: dict[str, Any]) -> str:
    return f"""\
# Generated by SMBPal for connection {connection['id']}. Do not edit.
[Unit]
Description=SMBPal automount for {connection['mountpoint']}

[Automount]
Where={connection['mountpoint']}
# TimeoutIdleSec is deliberately unset. M0 §4 watched a background desktop
# process re-trigger the automount 80 s after boot without the user touching
# anything, so idle unmounting cannot be relied on to happen at all.

[Install]
WantedBy=multi-user.target
"""
